# Generated by Django 2.2 on 2020-01-25 13:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('typ', models.CharField(choices=[('Contact', 'Contact'), ('Feedback', 'Feedback'), ('Visiting Request', 'Visiting Request'), ('Report', 'Report'), ('Offer', 'Offer')], default='Contact', max_length=45, verbose_name='Type')),
                ('status', models.CharField(choices=[('New', 'New'), ('Read', 'Read'), ('Inactive', 'Inactive')], default='New', max_length=45)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 1, 25, 13, 26, 4, 176845, tzinfo=utc))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2020, 1, 25, 13, 26, 4, 176845, tzinfo=utc))),
            ],
        ),
    ]
