# Generated by Django 2.2 on 2020-02-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0002_auto_20200125_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='purpose',
            field=models.CharField(default='N/A', max_length=255),
        ),
    ]
