# Generated by Django 2.2 on 2020-02-02 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0003_message_purpose'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=255, null=True)),
                ('short_address', models.CharField(max_length=255, null=True)),
                ('long_address', models.TextField(null=True)),
            ],
        ),
    ]
