# Generated by Django 2.2 on 2020-02-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0005_auto_20200202_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecontact',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sitecontact',
            name='long_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitecontact',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sitecontact',
            name='short_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
