# Generated by Django 2.2 on 2020-02-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.PositiveSmallIntegerField(choices=[(1, 'Home'), (2, 'About Us')], unique=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('heading', models.EmailField(blank=True, max_length=255, null=True)),
                ('short_description', models.CharField(blank=True, max_length=255, null=True)),
                ('long_description', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/uploads/cms/')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='static/uploads/cms/')),
                ('status', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Active'), (2, 'Inactive')], null=True)),
            ],
        ),
    ]
