# Generated by Django 2.2 on 2020-02-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='heading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
